In [8]:
import numpy as np

# 1. Accessing a specific element from a 2D array
a = np.array([[10, 20], [30, 40]])
print(f"Indexing:{a[0, 1]}\n")

# 2. Slicing a 1D array
b = np.array([0, 1, 2, 3, 4, 5])
print(f"Slicing:{b[1:5:2]}\n")

# 3. Column slicing in a 2D array
c = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Column slicing:\n{c[:, 1:]}\n")

# 4. Reshaping and flattening an array
d = np.array([1, 2, 3, 4, 5, 6])
d2 = d.reshape((2, 3))
print(f"Reshaped:\n{d2}\n")
print("Flattened:", d2.ravel())

Indexing:20

Slicing:[1 3]

Column slicing:
[[2 3]
 [5 6]]

Reshaped:
[[1 2 3]
 [4 5 6]]

Flattened: [1 2 3 4 5 6]
