In [4]:
import numpy as np

#Vectorization: Element-wise addition with scalar
a = np.array([1, 2, 3])
b = a + 10
print("Vectorization:", b)

#Broadcasting: Adding 1D array to 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([1, 0, 1])
print("\nBroadcasting:\n", a + b)

#Matrix multiplication using np.dot
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
print("\nMatrix multiplication:\n", result)

#Element-wise multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = a * b
print("\nElement-wise multiplication:\n", result)

Vectorization: [11 12 13]

Broadcasting:
 [[2 2 4]
 [5 5 7]]

Matrix multiplication:
 [[19 22]
 [43 50]]

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
