In [3]:
import tensorflow as tf

# Scalar
a = tf.constant(5)

# Vector
b = tf.constant([1, 2, 3])

# Matrix
c = tf.constant([[1, 2], [3, 4]])

# Tensor
d = tf.random.uniform([2, 3, 4])  # 3D tensor

print(f"{a}\n\n{b}\n\n{c}\n\n{d}")


5

[1 2 3]

[[1 2]
 [3 4]]

[[[0.44063938 0.23931599 0.6029122  0.6066133 ]
  [0.239663   0.96391296 0.28881228 0.6458893 ]
  [0.33104157 0.53886974 0.260633   0.25020576]]

 [[0.21134794 0.58135855 0.98154616 0.3980441 ]
  [0.47161818 0.06000829 0.17783403 0.90665257]
  [0.7551844  0.7231742  0.67384565 0.20821714]]]
